name: Build and push to PyPI 🐍

on:
  release:
    types: [ published ]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        
      - name: Install poetry
        run: python3 -m pip install poetry
        
      - name: Install dependencies
        run: python3 -m poetry install
      
      - name: Build and release package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m poetry config pypi-token.pypi $PYPI_TOKEN 
          python3 -m poetry publish --build
